services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: message-db
    environment:
      POSTGRES_DB: message
      POSTGRES_USER: message
      POSTGRES_PASSWORD: message
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
