[package]
name = "message_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
env_logger = "0.11.3"
dotenv = "0.15.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }