CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY ("id")
);-- Add up migration script here
