//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "consumptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Uuid,
    pub place_id: i64,
    pub spending_category_id: i64,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::places::Entity",
        from = "Column::PlaceId",
        to = "super::places::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Places,
    #[sea_orm(
        belongs_to = "super::spending_categories::Entity",
        from = "Column::SpendingCategoryId",
        to = "super::spending_categories::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SpendingCategories,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::places::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Places.def()
    }
}

impl Related<super::spending_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpendingCategories.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
