//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod consumptions;
pub mod monthly_budgets;
pub mod places;
pub mod settings;
pub mod spending_categories;
pub mod tokens;
pub mod users;
