//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::consumptions::Entity as Consumptions;
pub use super::monthly_budgets::Entity as MonthlyBudgets;
pub use super::places::Entity as Places;
pub use super::settings::Entity as Settings;
pub use super::spending_categories::Entity as SpendingCategories;
pub use super::tokens::Entity as Tokens;
pub use super::users::Entity as Users;
