//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::places::Entity as Places;
pub use super::settings::Entity as Settings;
pub use super::tokens::Entity as Tokens;
pub use super::users::Entity as Users;
